### ISSUE TITLE
Make upload button icon configurable

### ISSUE THREAD

**Issue by torbjornlarssen** [FriendsOfFlarum/upload#114]
My test users interpret the "file-o" icon as "new file/thread/something". 
Paperclip is pretty universally for "attach".

**Comment by luceos** [comment]
Good point, but let's make it configurable then.

**Comment by clarkwinkelmann** [comment]
This issue has been stale for a while and probably won't be implemented anytime soon.

The icon can be customized via CSS for those that wish to change it.

Closing this for now.
