### ISSUE TITLE
Make file download more intuitive

### ISSUE THREAD

**Issue by BertrandGouny** [FriendsOfFlarum/upload#131]
- flagrow/upload extension version: 0.6.0
- flarum version: 0.1.0-beta.7

Hello,
thanks for this great pulgin, 

I had one feedback from a user who thinks that it's a bit tricky to download a file: 
- we have to click on the button with the icon only.
- other buttons just do nothing, that is confusing.

What do you think to make all buttons (icon, name, size) clickable to download a file ?

By the way it would be nice to add a classname to ButtonGroup in 
**/resources/templates/file.blade.php** so customization would be easier :)

**Comment by luceos** [comment]
@BertrandGouny feel free to PR the classname to the file. Thanks for your feedback I'm aware the extension needs some love again. I'm tied up with another one for the time being, but I'll take the request along for the next overhaul.
