### ISSUE TITLE
Option to delete orphan files?

### ISSUE THREAD

**Issue by poVoq** [FriendsOfFlarum/upload#154]
- flagrow/upload extension version: latest
- flarum version: 0.1.0-beta.7.1
- upload adapter causing issues: local

---

It seems like files uploaded in topics that are later deleted or removed stay in the system? Would it be possible to have some sort of administrator option to purge all orphan files?
How would I go about deleting them manually?

Thanks!

**Comment by luceos** [comment]
Hi @poVoq ,

Upload at some point received a valuable tool which stores information about what file was uploaded where and to what post/discussion. In future versions there will be an option to delete media for posts that no longer exist.

I'd gladly add the functionality now, but I have other responsibilities that are of higher priority sadly.

Thanks for your understanding.

**Comment by BroxiNagil** [comment]
I'm as well interrested in somehow cleanup function ;-) apart from that .... great plugin !!!

**Comment by luceos** [comment]
After flarum beta 8 is released I'll be able to revisit this extension and bundle some new features into it..

**Comment by usama-asfar** [comment]
wating for the option to delete media which had deleted on the forum.

**Comment by omergoktas** [comment]
That would be a useful feature

**Comment by BBaoVanC** [comment]
Any news on this? I think this is a pretty important feature.

**Comment by BrianOtto** [comment]
I would like to see this feature too.

**Comment by luceos** [comment]
I'll look at releasing the new version this week 👍 I'm sorry, other things have been pushing this on the backlog.

**Comment by DavideIadeluca** [comment]
Resolved with [1.3.0-beta.1](https://github.com/FriendsOfFlarum/upload/compare/1.2.3...1.3.0-beta.1)
