### ISSUE TITLE
Duplicite foreign keys

### ISSUE THREAD

**Issue by juraJD7** [FriendsOfFlarum/upload#158]
- flagrow/upload extension version: <0.7.0>
- flarum version: 0.1.0-beta8.1
- upload adapter causing issues: <>
- mimetype configurations: <>

---

Foreign keys flagrow_file_downloads_actor_id_foreign, flagrow_file_downloads_discussion_id_foreign and flagrow_file_downloads_file_id_foreign are not forum prefixed.

Causes duplicite key error when enabling extension.

**Comment by broxinagil** [comment]
I've just discovered same issue using multiple installs on same database. Maybe this is not an issue on the Extension itself but in Illuminate Database core ?

**Comment by clarkwinkelmann** [comment]
I think that's a Laravel issue and I think it has been fixed. Not sure if we have the fix in the current version of Illuminate dependencies we use for Flarum.

Let us know if you experience this again and we'll look into it. Closing the issue for now.
