### ISSUE TITLE
Certain sized images throw an error upon uploading

### ISSUE THREAD

**Issue by Ralkage** [FriendsOfFlarum/upload#160]
- flagrow/upload extension version: 0.7.1
- flarum version: 0.1.0-beta.8.1
- upload adapter causing issues: local
- mimetype configurations: local

---

This bug initially stemmed from an investigation with Flagrow Upload throwing up an error when Reflar Gamification was enabled. I have recently debunked that report and ended up leading into a different but possibly similar bug to the one described by @010101 [here](https://discuss.flarum.org/d/5588-gamification-by-reflar/296).

In order to reproduce this bug, I have provided two of the same images with slight differences (file size and resolution). The extension settings can be set as default such as the image file size. Or, if you deem that a possible issue, try increasing the max size to 4112 kilobytes? 🤔 

**Test 1: The Not-So-Much-Working Version**
1. Attempt to upload this image by starting a new discussion (Just click the button, no title or body needed)(Take note that the file size shows as 1.99MB with a resolution of 3323x2215)
![test1-not-working-image](https://user-images.githubusercontent.com/2059356/50545004-2fd5ef80-0bd5-11e9-9792-2fddf60896d5.jpg)

2. BEHOLD! HERE BE ERROR!
![image](https://user-images.githubusercontent.com/2059356/50545064-855ecc00-0bd6-11e9-95c1-2c5543ed06d5.png)

3. From this point, you won't be able to upload any other images so go ahead and refresh the page to proceed to test 2.

**Test 2: The Actually-Working Version**
1. Attempt to upload this image by starting a new discussion (Be sure to do step 3 in the first test BEFORE THIS POINT just click the button, no title or body needed)(Take note that the file size shows as 2.00MB with a resolution of 3322x2214)
![test2-working-image](https://user-images.githubusercontent.com/2059356/50545200-ad036380-0bd9-11e9-9efd-2c17890b7a78.jpg)

2. BEHOLD!....No errors! 👺 
![image](https://user-images.githubusercontent.com/2059356/50545213-78dc7280-0bda-11e9-9b36-3e7cfe3091fc.png)

**Test 3 The BONUS ROUND:**
1. This test includes a bonus image that has a really ridiculous 4K resolution (6800x3800) and a small file size (950KB)

2. Attempt to upload this image by starting a new discussion (Be sure to do step 3 in the first test BEFORE THIS POINT just click the button, no title or body needed)
![test3](https://user-images.githubusercontent.com/2059356/50545237-43845480-0bdb-11e9-94d5-d48faefba69e.jpg)

3. BE HOLD?...The same error makes it's dreadful return :(
![image](https://user-images.githubusercontent.com/2059356/50545064-855ecc00-0bd6-11e9-95c1-2c5543ed06d5.png)

There we no console or Flarum related logs so a little light-bulb turned on in my head and told me to take a look at my PHP error logs.

[PHP Error Log - 30-Dec-2018.txt](https://github.com/flagrow/upload/files/2716992/PHP.Error.Log.-.30-Dec-2018.txt)

**^^^HERE BE THE SAUCE OF THE ISSUE!^^^**

Sorry for being so animated at 2:34 AM and including so much info, but I always believe all information is good information for debugging errors and of course...bugs 🐛 ❤️

**Comment by Ralkage** [comment]
And then I realized that this error is actually caused by the PHP upload max filesize limit being reached from my php.ini 🤦‍♂️ 

It makes no sense because the image from test 3 doesn't reach the max filesize and the image from test 1 does. Both images are unable to be processed/uploaded despite the filesize differences.

Additional logs via Flarum logs that actually produced:

[flarum-2018-12-30.log](https://github.com/flagrow/upload/files/2716998/flarum-2018-12-30.log)

**Comment by clarkwinkelmann** [comment]
Seems like this has been resolved a long time ago.

The max file size defined by Upload only works for files that are below the PHP file limit. If the PHP file limit is reached, the requests fails at the webserver level, before Flarum even boots.
