### ISSUE TITLE
Working with Digital Ocean Spaces

### ISSUE THREAD

**Issue by olekukonko** [FriendsOfFlarum/upload#162]
I was able to make this work with digital ocean spaces.  Do you want a pull request?

**Comment by clarkwinkelmann** [comment]
@olekukonko sorry we never replied to your issue last year. Are you still interested in submitting a PR ? We will soon release the FriendsOfFlarum version of the extension, so your changes will maybe need a few adjustments but we would be happy to incorporate them! Feel free to go ahead and submit a PR.

**Comment by uamv** [comment]
I could make use of this and would love to see it integrated if you still have the code lying around, @olekukonko.

**Comment by imorland** [comment]
Closing as stale. Please feel free to re-open if neccessary
