### ISSUE TITLE
S3 Compatible Alts

### ISSUE THREAD

**Issue by tankerkiller125** [FriendsOfFlarum/upload#164]
- flagrow/upload extension version: N/A
- flarum version: N/A
- upload adapter causing issues: AWS S3
- mimetype configurations: N/A

---

Please consider adding support for S3 compatible storage services like minio, this should be a minimal change. Really only a host option would need to be added.

**Comment by clarkwinkelmann** [comment]
@tankerkiller125 do you still think this would be a useful addition ? Do you know if the S3 client can work with third-party hosts ? If the S3 library cannot be used out of the box for this, I think we should consider it a "won't fix".

**Comment by tankerkiller125** [comment]
The Flysystem S3 Driver works with Minio very well, https://laravel-news.com/minio-s3-compliant-storage has some documentation on the S3 config options that have to be used, most notably `use_path_style_endpoint` and `endpoint`

I still believe that this would be very useful, especially for large websites who use load balancing setups and need a central file store that's not on a cloud provider for regulation reasons or privacy reasons.
