### ISSUE TITLE
Multiple uploads

### ISSUE THREAD

**Issue by JonasLTU** [FriendsOfFlarum/upload#165]
- flagrow/upload extension version: 0,7,1
- flarum version: 0.1.0-beta.8
- upload adapter causing issues: local
- mimetype configurations: jpg

---

Hello,
I have an inquiry - I have a problem when I try to do several image uploads with Paste (Ctrl+V). Uploads in the first reply work fine. If I later try to do another uploads (by pasting clipboard) in other replies in the same or other discussions, the image gets uploaded and the plugin returns BBCODE, but the BBCODE doesn't get included in the reply thread (if I do it in other discussion, I get redirected to previous discussion). 
View with annotations: https://files.anuzis.lt/MwZmDd8F37.png

**Comment by clarkwinkelmann** [comment]
This will be fixed in the upcoming FriendsOfFlarum version of the extension. There was an issue with copy-pasting only working properly for the first reply.
