### ISSUE TITLE
can't upload files

### ISSUE THREAD

**Issue by AkitoSilver** [FriendsOfFlarum/upload#167]
- flagrow/upload extension version: ^0.7.1
- flarum version: 0.1.0-beta.8.1
- upload adapter causing issues: <local>
I can't upload any files and I don't really know what is going on,here is my error log:
`[2019-02-20 14:58:43] production.ERROR: Error: Class 'Ramsey\Uuid\Uuid' not found in /data/www/default/vendor/flagrow/upload/src/Repositories/FileRepository.php:60
Stack trace:
#0 /data/www/default/vendor/flagrow/upload/src/Commands/UploadHandler.php(96): Flagrow\Upload\Repositories\FileRepository->createFileFromUpload(Object(Symfony\Component\HttpFoundation\File\UploadedFile), Object(Flarum\User\User))
#1 [internal function]: Flagrow\Upload\Commands\UploadHandler->Flagrow\Upload\Commands\{closure}(Object(Zend\Diactoros\UploadedFile), 0)
#2 /data/www/default/vendor/illuminate/support/Collection.php(861): array_map(Object(Closure), Array, Array)
#3 /data/www/default/vendor/flagrow/upload/src/Commands/UploadHandler.php(139): Illuminate\Support\Collection->map(Object(Closure))
#4 /data/www/default/vendor/illuminate/bus/Dispatcher.php(90): Flagrow\Upload\Commands\UploadHandler->handle(Object(Flagrow\Upload\Commands\Upload))
#5 /data/www/default/vendor/illuminate/pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Flagrow\Upload\Commands\Upload))
#6 /data/www/default/vendor/illuminate/pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Flagrow\Upload\Commands\Upload))
#7 /data/www/default/vendor/illuminate/bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#8 /data/www/default/vendor/illuminate/bus/Dispatcher.php(76): Illuminate\Bus\Dispatcher->dispatchNow(Object(Flagrow\Upload\Commands\Upload))
#9 /data/www/default/vendor/flagrow/upload/src/Api/Controllers/UploadController.php(52): Illuminate\Bus\Dispatcher->dispatch(Object(Flagrow\Upload\Commands\Upload))
#10 /data/www/default/vendor/flarum/core/src/Http/RouteHandlerFactory.php(40): Flagrow\Upload\Api\Controllers\UploadController->handle(Object(Zend\Diactoros\ServerRequest))
#11 /data/www/default/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(67): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}(Object(Zend\Diactoros\ServerRequest), Array)
#12 /data/www/default/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\DispatchRoute->process(Object(Zend\Diactoros\ServerRequest), Object(Closure))
#13 /data/www/default/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#14 /data/www/default/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\SetLocale->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#15 /data/www/default/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(55): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#16 /data/www/default/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\AuthenticateWithHeader->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#17 /data/www/default/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(34): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#18 /data/www/default/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\AuthenticateWithSession->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#19 /data/www/default/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#20 /data/www/default/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\RememberFromCookie->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#21 /data/www/default/vendor/flarum/core/src/Http/Middleware/StartSession.php(62): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#22 /data/www/default/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\StartSession->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#23 /data/www/default/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(31): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#24 /data/www/default/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Api\Middleware\FakeHttpMethods->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#25 /data/www/default/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(29): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#26 /data/www/default/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\ParseJsonBody->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#27 /data/www/default/vendor/flarum/core/src/Api/Middleware/HandleErrors.php(42): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#28 /data/www/default/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Api\Middleware\HandleErrors->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#29 /data/www/default/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(83): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#30 /data/www/default/vendor/middlewares/request-handler/src/RequestHandler.php(84): Zend\Stratigility\MiddlewarePipe->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#31 /data/www/default/vendor/zendframework/zend-stratigility/src/Next.php(52): Middlewares\RequestHandler->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#32 /data/www/default/vendor/middlewares/base-path-router/src/BasePathRouter.php(97): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#33 /data/www/default/vendor/zendframework/zend-stratigility/src/Next.php(52): Middlewares\BasePathRouter->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#34 /data/www/default/vendor/middlewares/base-path/src/BasePath.php(53): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#35 /data/www/default/vendor/zendframework/zend-stratigility/src/Next.php(52): Middlewares\BasePath->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#36 /data/www/default/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(83): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#37 /data/www/default/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(72): Zend\Stratigility\MiddlewarePipe->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\EmptyPipelineHandler))
#38 /data/www/default/vendor/zendframework/zend-httphandlerrunner/src/RequestHandlerRunner.php(95): Zend\Stratigility\MiddlewarePipe->handle(Object(Zend\Diactoros\ServerRequest))
#39 /data/www/default/vendor/flarum/core/src/Http/Server.php(46): Zend\HttpHandlerRunner\RequestHandlerRunner->run()
#40 /data/www/default/public/index.php(22): Flarum\Http\Server->listen()
#41 {main}
`
And here is my composer.json:
`{
    "name": "flarum/flarum",
    "description": "Delightfully simple forum software.",
    "type": "project",
    "keywords": ["forum", "discussion"],
    "homepage": "https://flarum.org/",
    "license": "MIT",
    "authors": [
        {
            "name": "Toby Zerner",
            "email": "toby.zerner@gmail.com"
        },
        {
            "name": "Franz Liedke",
            "email": "franz@develophp.org"
        }
    ],
    "support": {
        "issues": "https://github.com/flarum/core/issues",
        "source": "https://github.com/flarum/flarum",
        "docs": "https://flarum.org/docs/"
    },
    "require": {
        "csineneo/lang-simplified-chinese": "v0.1.0-beta.8.23",
        "flagrow/upload": "^0.7.1",
        "flarum/approval": "^0.1.0",
        "flarum/auth-facebook": "^0.1.0",
        "flarum/auth-github": "^0.1.0",
        "flarum/auth-twitter": "^0.1.0",
        "flarum/bbcode": "^0.1.0",
        "flarum/core": "^0.1.0",
        "flarum/emoji": "^0.1.0",
        "flarum/flags": "^0.1.0",
        "flarum/lang-english": "^0.1.0",
        "flarum/likes": "^0.1.0",
        "flarum/lock": "^0.1.0",
        "flarum/markdown": "^0.1.0",
        "flarum/mentions": "^0.1.0",
        "flarum/pusher": "^0.1.0",
        "flarum/statistics": "^0.1.0",
        "flarum/sticky": "^0.1.0",
        "flarum/subscriptions": "^0.1.0",
        "flarum/suspend": "^0.1.0",
        "flarum/tags": "^0.1.0",
        "jjandxa/flarum-ext-chinese-search": "^0.0.8"
    },
      "config": {
        "preferred-install": "dist",
        "sort-packages": true
    },
    "minimum-stability": "beta",
    "prefer-stable": true
}
`

**Comment by Ralkage** [comment]
Hi @AkitoSilver, are you still experiencing this issue? I know this issue has been opened for a while without a response so I'll wait 72 hours for your reply and will conclude this issue as resolved otherwise.

**Comment by Ralkage** [comment]
Hi @AkitoSilver,

I have given you more than enough time to respond so before I close this issue I will provide you with two possible solutions since it looks like you are missing the `ramsey/uuid` package:

1. Run `composer require ramsey/uuid`  in the root of your Flarum installation to install the missing package.

If that fails then...

2. Reinstall this extension by running `composer remove flagrow/upload` in the root of your Flarum installation followed by `composer require flagrow/upload`.

Hope this helps :)
