### ISSUE TITLE
Url in upl-image-preview misses dot in extension

### ISSUE THREAD

**Issue by stijnfrishert** [FriendsOfFlarum/upload#168]
- flagrow/upload extension version: 0.7.1
- flarum version: 0.1.0-beta.8.1
- upload adapter causing issues: local
- mimetype configurations: ^image\/.* => local

---

When uploading an image, the following code is outputted: `[upl-image-preview url=...]`. The image isn't shown. Clicking on the url tells me the page could not be found.

The url itself misses a . before the extension (so in this case it ends in `...420351696896-njpeg]`. changing that to `...420351696896-n.jpeg]` fixes this issue.

**Comment by stijnfrishert** [comment]
Found the problem!

Local.php `str_replace()` introduces the problem when `public_path()` == `'.'`.

**Comment by luceos** [comment]
I am unsure whether this is an issue with your environment (windows perhaps) or the configuration (public_path) because technically public_path() should always return a full absolute path to the docroot or deeper..

If you are able to clarify I can do something about this.

**Comment by stijnfrishert** [comment]
Yeah, this was an issue on my side, because public_path was set up to be defined as `.` (which is not absolute in the slightest).

I'm not a PHP developer by trade, so with my little experience I thought it was safe to use a relative path there. Opened this issue because you might consider sanitizing that for "people like me", though I'd understand you'd flag this as a non-issue. :)

**Comment by clarkwinkelmann** [comment]
I'm closing this issue as it seems it has been resolved (since some time...). Feel free to let us know if you still have issues, we'll re-open it.
