### ISSUE TITLE
Does not parse [upl macros

### ISSUE THREAD

**Issue by haarp** [FriendsOfFlarum/upload#181]
- flagrow/upload extension version: 0.7.1
- flarum version: 0.1.0-beta.8
- upload adapter causing issues: local
- mimetype configurations: <eg ^image\/.* => local>

Hi,

just set up a new Flarum and installed this plugin with Composer. Files upload fine. But the [upl macros are not parsed, so instead of a preview, Ithe posts contain a literal

    [upl-image-preview url=...jpeg]

I'm not sure what to make of this.

Thanks!

**Comment by haarp** [comment]
Clearing the cache helps. This should be done right after installation of the plugin, before doing any uploads. Maybe this should be added to README.md? It only mentions clearing the cache adter upgrading the plugin, not on fresh installs.

**Comment by clarkwinkelmann** [comment]
This will be fixed in the upcoming FriendsForFlarum release. The formatter cache was not automatically cleared when the extension was enabled.
