### ISSUE TITLE
Uploading a file does not set post_id and discussion_id in db

### ISSUE THREAD

**Issue by andreasjacobsen93** [FriendsOfFlarum/upload#183]
- flagrow/upload extension version: 0.7.1
- flarum version: 0.1.0-beta.10
- upload adapter causing issues: local
- mimetype configurations: ^image\/.* => local, pdf|doc|docx|xls|xlsx => local

There is two columns in the database created from migration 2016_11_03_000000_create_flagrow_files.php. The problem is that those two fields are not set when a file is uploaded through the forum interface.

It would make sense to store the id of post and discussion, which would make it possible to later delete all files related to a post or discussion, or restrict access to files based on discussion permissions.

**Comment by luceos** [comment]
Yes that was the intention, I never found a way to make it work for new discussions.

**Comment by andreasjacobsen93** [comment]
We are looking at a solution, that listens for a post save and searches for the upl-file tag, it then parses the post content and updates the file with a post id.
But there could be a smarter way?

**Comment by clarkwinkelmann** [comment]
There's no magic solution. We'll have to implement it at some point I guess.

Closing this issue because the missing relationship is already tracked in #155
