### ISSUE TITLE
Custom Template Type?

### ISSUE THREAD

**Issue by shangjiaxuan** [FriendsOfFlarum/upload#187]
- flagrow/upload extension version: 0.7.1
- flarum version: 0.1.0-beta.10
- upload adapter causing issues: local
- mimetype configurations: specify below

---

The extension is working with normal uploads and previews of images, but I was trying to make short clips of video previewed instead of downloaded as file. 

Currently setting the videos' template to image, and then removing the headers, and using auto-video(fof/formatting) or direct html code will allow using uploaded video to be previewed(`<video controls="" src={URL}></video>`). Using file upload does not give the url in the text editor, thus you need to go with image preview.

It will be quite helpful if I could just specify a new template myself or elsewhere. I was looking into
`src\Templates`, `src\Api`, `src\Listeners\`, etc and settings and values in the database. But simply copying the image-preview version and changing the image to video, and changing the entry in database to add a new template, add an entry in the locale file do not fix the issue. I now cannot get into the admin page for upload, and uploading videos returns `422`  type not allowed.

What files I might be missing?

**Comment by shangjiaxuan** [comment]
There was a similar issue #146 about using images.

**Comment by shangjiaxuan** [comment]
Added the registrations at src/Helpers/Settings.php, corrected a few unchanged names, corrected the files under resource/templates, and the admin panel is working again. But the the video is not displaying correctly, and the uploader still emits 422.

MIME configuration:
Video: (video\/(3gpp|mp4|mpeg|quicktime|webm)
Image: (image\/(gif|jpeg|png))|(audio\/(aiff|midi|mpeg|mp4))
File: (application\/(x-(7z|rar)-compressed|zip|arj|x-(bzip2|gzip|lha|stuffit|tar)|pdf))

**Comment by luceos** [comment]
have you tried returning just the link and combining that with fof/formatting to render it to a video, or is it a custom video provider service?

**Comment by shangjiaxuan** [comment]
> have you tried returning just the link and combining that with fof/formatting to render it to a video, or is it a custom video provider service?

I thought in order to use the upload extension, one would need to use a bbcode associated with the extension to work (To upload a short clip and make it preview-able would first need to upload it, thus currently requires a bbcode. Only changing from returning `[upl-image-preview url={URL}]` to `{URL}` does not give the actual uploaded URL in the text editor).

**Comment by clarkwinkelmann** [comment]
Technically, it should be possible. The extension allows adding new templates that extend `AbstractTemplate` via a service provider (by calling `addRenderTeamplte` on the `Settings` object as you might have already found ?)

A template similar to the full image, but with a `video` tag should be easily doable.

Let us know if there's any specific issue we can help with, otherwise we'll close this issue.

The FriendsOfFlarum version of the package will be released very soon. But apart from the namespace changes (`Flagrow` to `FoF`), everything still works exactly the same for adding new templates,

**Comment by johnlewissims** [comment]
Has there been any development here?  I'd love to have the ability for users to play videos directly instead of having to download them.
