### ISSUE TITLE
Loading Progress and Preview

### ISSUE THREAD

**Issue by anlatmatik** [FriendsOfFlarum/upload#188]
flagrow/upload extension version: 0.7.1
flarum version: Flarum 0.1.0-beta.11 
upload adapter causing issues: local
mimetype configurations: ^image/.* => local
1) show loading progress can be added

https://ibb.co/mq6f10K

2)Preview an image after upload

https://ibb.co/bLb0HZr

Can these features be added to the plug-in

**Comment by anlatmatik** [comment]
> 1. show loading progress can be added
> 
> https://ibb.co/mq6f10K
> 
> 2)Preview an image after upload
> 
> https://ibb.co/bLb0HZr
> 
> Can these features be added to the plug-in

**Comment by zerosonesfun** [comment]
Rather than starting a new issue I will add to this. It’s odd though because this issue is from 2019 but I know at one point in 2020 the loading spinner was fixed. I think due to beta 14, the loading spinner may be broken again.

**Comment by clarkwinkelmann** [comment]
It's actually better to create a new issue, in particular because new issues are at the top, and we have so many issues opened on this repo :hear_no_evil: 

This will be addressed in #247
