### ISSUE TITLE
How to download attachments directly?

### ISSUE THREAD

**Issue by qazwsdc** [FriendsOfFlarum/upload#200]
How to download attachments directly without going through php proxy?
I'm using qiniu cdn and I want to download things directly from qiniu cloud.

**Comment by DavideIadeluca** [comment]
@qazwsdc For technical support queries (which are not a bug report or feature request) please ask a new question at https://discuss.flarum.org/t/support or reply in the discussion https://discuss.flarum.org/d/4154-friendsofflarum-upload-the-intelligent-file-attachment-extension
