### ISSUE TITLE
support fof/formatting bbcode

### ISSUE THREAD

**Issue by unknowndevice** [FriendsOfFlarum/upload#228]
Right now the tag format is [upl-image-preview url=//url]. it would be great if the bbcode in fof/formatting [img]url[/img] was supported

**Comment by clarkwinkelmann** [comment]
You can already create custom templates for fof/upload via PHP.

If merged, the PR #226 will make it even easier to add custom templates and will also add a built-in template that works with AutoImage.

**Comment by unknowndevice** [comment]
excellent. I'll close this issue then. thanks!
