### ISSUE TITLE
Regarding the syntax problem of inserting the editor after uploading the file.

### ISSUE THREAD

**Issue by philipsc** [FriendsOfFlarum/upload#233]
I noticed that the content inserted into the editor after uploading using it is 
`[upl-image-preview url=https://yourdomainurl/time/name.jpeg]`, it is neither UBB nor markdown, which leads to if I uninstall this plugin , It will not be displayed on the page. I think the inserted format should be compatible with UBB and markdown.

**Comment by clarkwinkelmann** [comment]
That's intentional as it enables the files permission and download counting features.

If #226 is merged it'll bring a built-in template for inserting links without any custom bbcode, with the downside of not being able to use the features described above.

**Comment by philipsc** [comment]
Ok, I see
