### ISSUE TITLE
Add support for Tencent COS | 请求增加腾讯云对象存储支持

### ISSUE THREAD

**Issue by AnotiaWang** [FriendsOfFlarum/upload#235]
Would you please add support for Tencent Cloud Obeject Storage?
the website is https://intl.cloud.tencent.com/product/cos or https://cloud.tencent.com/product/cos (in Chinese)
Thanks!

**Comment by clarkwinkelmann** [comment]
I can't make any promise but I found a Flysystem driver already exists so it shouldn't be too complicated to implement, even for a third-party https://github.com/overtrue/flysystem-cos

**Comment by AnotiaWang** [comment]
> I can't make any promise but I found a Flysystem driver already exists so it shouldn't be too complicated to implement, even for a third-party https://github.com/overtrue/flysystem-cos

Oh, qcloud is actually tencent COS. Got it, thanks

**Comment by AnotiaWang** [comment]
Still dont know how to use it🤧
