### ISSUE TITLE
What to do with adapter suggestions?

### ISSUE THREAD

**Issue by clarkwinkelmann** [FriendsOfFlarum/upload#237]
I'm calling for the FriendsOfFlarum members feedback on this.

The number of adapter suggestions keep growing, and accounts for a good number of the open issues here.

We probably won't implement any of them any time soon, if ever.

We need to decide on a strategy:

- Do we keep them open, close them, move them to Discuss, elsewhere?
- Do we actually want to implement any of them? Which ones should be prioritized? Should we have some kind of voting system?

I don't like keeping those issues open. It makes it look like we might implement them at some point, though with our current manpower it's unlikely this happens without financial backing.

---

My suggestion on the matter is that we stop accepting driver suggestions, at least on GitHub. We close all issues, and just maintain the existing adapters.

New adapters can be PRd or commissioned, but there needs to be a clear public benefit of having them in the main package.

I'm hoping we get https://github.com/FriendsOfFlarum/filesystem-drivers ready at some point and use it here, at which time it'll make sense to add more drivers to a package that's all about drivers. We could revisit a proper voting system for new drivers at that point.

Thoughts?

**Comment by luceos** [comment]
How about we add this info to the readme. And offer the two ways you mention, but allow commissions against a base price with a donation (eg $ 200) to the oc?

**Comment by clarkwinkelmann** [comment]
Here's my proposal for the README:

> ## Additional adapters
> 
> As much as we would like to support all possible hosting services in the world, special consideration is given before accepting new adapters in the extension.
> Every additional bundled adapter means more maintenance work and more testing anytime we have to make breaking changes.
> 
> The process to introduce new bundled adapters is as follows:
> 
> - An adapter suggestion is posted on the [extension discussion on Discuss](https://discuss.flarum.org/d/4154) and is frequently requested by the community
> - A supported and popular [Flysystem driver](https://flysystem.thephpleague.com/) exists for the hosting method
> - All FoF members approve the addition of the driver
> 
> GitHub issues or pull requests about new adapters will be closed.
Please get in touch beforehand if you would like to help us implement a popular adapter.
> 
> If you need an adapter that isn't popular enough or want to accelerate its development, there are alternate options:
> 
> - Develop the adapter for yourself, using the events and classes provided by the extension
> - Sponsor the development by FriendsOfFlarum. Subject to approval by the collective, with a minimum donation of $200

We should add a wiki page about creating custom adapters. There's currently no documentation for people looking to create their own private adapters.

**Comment by luceos** [comment]
I think we should really spend some time on filesystem drivers, especially now that we're closing in on stable.. We can then divert all that logic to that extension.
