### ISSUE TITLE
qiniu upload fail | 七牛上传失败

### ISSUE THREAD

**Issue by milu2003** [FriendsOfFlarum/upload#241]
![image](https://user-images.githubusercontent.com/15957433/97887543-07852200-1d65-11eb-9f2f-ba852b496808.png)

![image](https://user-images.githubusercontent.com/15957433/97887577-12d84d80-1d65-11eb-9585-0bf986084944.png)

upload this file:

![image](https://user-images.githubusercontent.com/15957433/97887652-25eb1d80-1d65-11eb-90fd-8116fe46c443.png)

![image](https://user-images.githubusercontent.com/15957433/97887744-44e9af80-1d65-11eb-84d2-e576b0a13c87.png)

```
{"errors":[{"status":"500","code":"unknown"}]}
```

```
composer require overtrue/flysystem-qiniu
```

![image](https://user-images.githubusercontent.com/15957433/97888024-9d20b180-1d65-11eb-937e-6c52b3df4807.png)

What is the problem

**Comment by clarkwinkelmann** [comment]
Check the log file at `<flarum>/storage/logs` for the full error message.

**Comment by milu2003** [comment]
@clarkwinkelmann 

Thank you. The problem is solved
Just install the Exif extension



![image](https://user-images.githubusercontent.com/15957433/97901690-78353a00-1d77-11eb-9278-659a29db7a6e.png)

```
Reading Exif data is not supported by this PHP installation
```


![image](https://user-images.githubusercontent.com/15957433/97901785-98fd8f80-1d77-11eb-8d7d-f03e003b2109.png)

**Comment by clarkwinkelmann** [comment]
Great news :smiley: :+1:
