### ISSUE TITLE
Beta 14.1 install does not show in Admin Menu

### ISSUE THREAD

**Issue by jaredwolff** [FriendsOfFlarum/upload#245]
After successfully installing as seen in #243, I noticed that there's no menu.

<img width="1792" alt="Screen Shot 2020-11-12 at 1 53 31 PM" src="https://user-images.githubusercontent.com/1015795/98983225-78a7a080-24ee-11eb-8cf0-2fdc26dee961.png">

It should on the left sidebar right?

**Comment by luceos** [comment]
Try clearing cache.. not sure though.

**Comment by jaredwolff** [comment]
I did try that. Super weird. 

Is it expected that some of these plugins can't be disabled (no checkbox?)

**Comment by clarkwinkelmann** [comment]
The extension appears disabled in the screenshot (color of the icon)

I'm pretty sure there's a GitHub issue or forum discussion about the disappearing name+checkbox. It must be one of those browser-specific things. You could try with another browser.

Related but probably not the same https://github.com/flarum/core/issues/2386

**Comment by jaredwolff** [comment]
I'll take a look at it with Firefox (was using Safari)

**Comment by jaredwolff** [comment]
Looks like that did it. Worked in Firefox!

**Comment by clarkwinkelmann** [comment]
Safari has been causing us a lot of headache already. It really doesn't like the column layout we implemented for the extension list.

We will release a new extension list layout that doesn't use columns soon. Hopefully this will solve those problems for us.

**Comment by jaredwolff** [comment]
Awesome. Thanks @clarkwinkelmann
