### ISSUE TITLE
Watermark upload error : Call to undefined function FoF\Upload\Api\Controllers\array_get()

### ISSUE THREAD

**Issue by happytodev** [FriendsOfFlarum/upload#248]
Hello,

When I tried to upload picture for watermark (png or jpg), I had an error.

This is the content of error :
`[2020-11-28 17:05:48] flarum.ERROR: Error: Call to undefined function FoF\Upload\Api\Controllers\array_get() in /home/xxxxxxxxxxxxxxxxxxx/vendor/fof/upload/src/Api/Controllers/WatermarkUploadController.php:33`

I use Flarum 0.14 and this is the return of flarum info :

Flarum core 0.1.0-beta.14.1
PHP version: 7.4.11
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, bz2, calendar, ctype, curl, hash, filter, ftp, gettext, gmp, SPL, iconv, pcntl, readline, Reflection, session, standard, shmop, SimpleXML, mbstring, tokenizer, xml, bcmath, dom, fileinfo, gd, imap, intl, json, ldap, exif, mysqli, mysqlnd, PDO, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, xmlreader, xmlrpc, xmlwriter, xsl, zip
+----------------------+------------------+--------+
| Flarum Extensions    |                  |        |
+----------------------+------------------+--------+
| ID                   | Version          | Commit |
+----------------------+------------------+--------+
| flarum-lang-english  | v0.1.0-beta.14.1 |        |
| flarum-flags         | v0.1.0-beta.14.1 |        |
| flarum-approval      | v0.1.0-beta.14   |        |
| flarum-emoji         | v0.1.0-beta.14   |        |
| flarum-likes         | v0.1.0-beta.14   |        |
| flarum-lock          | v0.1.0-beta.14   |        |
| flarum-markdown      | v0.1.0-beta.14   |        |
| flarum-mentions      | v0.1.0-beta.14   |        |
| flarum-statistics    | v0.1.0-beta.14   |        |
| flarum-sticky        | v0.1.0-beta.14   |        |
| flarum-subscriptions | v0.1.0-beta.14   |        |
| flarum-suspend       | v0.1.0-beta.14   |        |
| flarum-tags          | v0.1.0-beta.14   |        |
| fof-upload           | 0.11.1           |        |
+----------------------+------------------+--------+

**Comment by clarkwinkelmann** [comment]
Thanks for the report! Fixed in version 0.11.2

**Comment by happytodev** [comment]
I confirm, it works now ! Thanks a lot.
