### ISSUE TITLE
Extension shows Error during uploading photos

### ISSUE THREAD

**Issue by patryk15x** [FriendsOfFlarum/upload#261]
The extension won't allow for uploading photos. Following error is displayed every time:
`Oops! Something went wrong. Please reload the page and try again.`
It worked for me last week and I did not change anything in setup since then. Tested on several forums from freeflarum platform.

**Comment by luceos** [comment]
Maybe you ran out of space. If you have access to the log file of flarum (or can enable debug) do so and report back with the error you see. If this is FreeFlarum, get their support.
