### ISSUE TITLE
Replace image preview template with markdown

### ISSUE THREAD

**Issue by askvortsov1** [FriendsOfFlarum/upload#268]
If it's just an image, using markdown would be simpler, better for editing after the fact, and would interface with the WYSWYG extension

**Comment by clarkwinkelmann** [comment]
While I do think it should be an option, the downside of markdown is that we can't use custom CSS to alter how it looks, or have wrapping DIVs for any purpose.

Though depending on the styling we want, maybe it's something we want to apply to all images without regard to whether it was uploaded or externally link, in that case it wouldn't matter and we could directly update the IMG template from TextFormatter.

**Comment by askvortsov1** [comment]
I think the templates that do have wrapping divs and stuff are fine to leave as is. Iirc there was one template that's just the image preview, I 2ws referring to that one.

**Comment by luceos** [comment]
image markdown template exists
