### ISSUE TITLE
Compatibility with beta 16

### ISSUE THREAD

**Issue by julienthomas** [FriendsOfFlarum/upload#272]
Hello.
The core beta 16 uses illuminate/validation v8 wich uses symfony5.
Passing file size is now deprecated when instancing `Symfony\Component\HttpFoundation\File\UploadedFile`, so the newly created instance is always flagged as invalid.
Possible solution (from `FoF\Upload\Repositories\FileRepository::moveUploadedFileToTemp`):
```
$file = new Upload(
    $tempFile,
    $upload->getClientFilename(),
    $upload->getClientMediaType(),
    $upload->getError(),
    true
);
```

**Comment by Gasjki** [comment]
I'm looking forward for the next release. I made a mistake and I updated my website and now I can't show my uploaded images anymore.
