### ISSUE TITLE
Beta.16 update upload bug

### ISSUE THREAD

**Issue by Miuss** [FriendsOfFlarum/upload#277]
Beta.16 update upload bug
I use dev-master 
![image](https://user-images.githubusercontent.com/26337587/112750414-106bde00-8ffb-11eb-9ee8-af7ab08360b5.png)

**Comment by imorland** [comment]
Please don't use `dev-master` - beta 16 support is work in progress at the moment and is currently being worked on. We will announce when this extension is ready for beta 16
