### ISSUE TITLE
Missing 'settings saved' translation

### ISSUE THREAD

**Issue by imorland** [FriendsOfFlarum/upload#288]
![image](https://user-images.githubusercontent.com/16573496/120676789-4cee0700-c48e-11eb-8179-bbaf9ad08e84.png)

**Comment by clarkwinkelmann** [comment]
I fixed the same issue in fof/pages https://github.com/FriendsOfFlarum/pages/commit/841c1e180e13f7993e1d217c8f01175c6f2ea6d7#diff-40a5adda4370d5e93ffef72b9b6dec35d3831f6e2bfc87ca0f4125bf462e96ca

Seems like this translation was removed from Flarum at some point. It wasn't very wise to rely on it in the first place
