### ISSUE TITLE
Media Manager Display Issue

### ISSUE THREAD

**Issue by imshuzai** [FriendsOfFlarum/upload#291]
## Bug Report

**Current Behavior**
Hello, I found an odd issue with the Media Manager. When the number of My Media is less than 20, everything is fine. But when the number of my media is 20 to 40, the files after 20(which will show in the second page) will show repeatedly. The most confusing thing is that when the number of My Media is greater than 40, files after 40(third page) will not be displayed.
I found this issue on both my host and freeflarum. I'm using beta16, but I tried on 1.0 and this issue still exists.

**Steps to Reproduce**
1. Upload more than 20 files.
2. Refresh and check Media Manager or My media.
3. Upload more than 40 files.
4. Refresh and check Media Manager or My media.

**Expected Behavior**
Show uploaded files correctly.

**Screenshots**
[![Rg1prR.gif](https://z3.ax1x.com/2021/07/02/Rg1prR.gif)](https://imgtu.com/i/Rg1prR)
[![Rg1APO.gif](https://z3.ax1x.com/2021/07/02/Rg1APO.gif)](https://imgtu.com/i/Rg1APO)

**Environment**
- Flarum version: 1.0.3/0.1.0-beta.16
- Extension version: 1.0.1/0.14.0
- Website URL: http://example.com
- Webserver: nginx
- Hosting environment: vps
- PHP version: 7.4.20
- Browser: chrome 91

```
Flarum core 1.0.3
PHP version: 7.4.20
Loaded extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, ctype, curl, dom, filter, ftp, gd, gettext, hash, iconv, intl, json, mbstring, SPL, session, pcntl, standard, PDO, mysqlnd, pdo_sqlite, Phar, posix, Reflection, pdo_mysql, shmop, SimpleXML, soap, sockets, sodium, mysqli, sysvsem, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, zip, fileinfo, exif, Zend OPcache
+----------------------+---------+--------+
| Flarum Extensions    |         |        |
+----------------------+---------+--------+
| ID                   | Version | Commit |
+----------------------+---------+--------+
| flarum-subscriptions | v1.0.0  |        |
| flarum-tags          | v1.0.3  |        |
| flarum-flags         | v1.0.0  |        |
| akr-chevereto        | 1.0.1   |        |
| fof-follow-tags      | 1.0.0   |        |
| flarum-suspend       | v1.0.0  |        |
| flarum-sticky        | v1.0.0  |        |
| flarum-statistics    | v1.0.0  |        |
| flarum-mentions      | v1.0.0  |        |
| flarum-markdown      | v1.0.1  |        |
| flarum-lock          | v1.0.0  |        |
| flarum-likes         | v1.0.0  |        |
| flarum-lang-english  | v1.0.0  |        |
| flarum-emoji         | v1.0.0  |        |
| flarum-bbcode        | v1.0.0  |        |
| flarum-approval      | v1.0.0  |        |
| fof-upload           | 1.0.1   |        |
+----------------------+---------+--------+
Debug mode: off
```

**Possible solution(s)**

**Additional Context**

**Comment by DavideIadeluca** [comment]
Thanks @imshuzai for the bug report. The issue has been resolved in the meantime, but with 1.5.0 a similar bug was introduced (see https://github.com/FriendsOfFlarum/upload/issues/395).

Therefore, this issue will be closed.
