### ISSUE TITLE
The button for uploading files gets too big while uploading

### ISSUE THREAD

**Issue by rafaucau** [FriendsOfFlarum/upload#296]
## Bug Report

**Current Behavior**
When I upload files, the upload button gets very large breaking the editor layout.

**Steps to Reproduce**
1. Open the editor
2. Upload files
3. Watch how the upload button behaves

**Expected Behavior**
Button should not get so big that it breaks the editor's layout

**Screenshots**
![image](https://user-images.githubusercontent.com/25438601/131409445-eace914a-cbed-48b2-92da-24bb34044853.png)

https://user-images.githubusercontent.com/25438601/131409355-f4ebb609-0a5a-40f1-b7f7-eea702660927.mp4

**Environment**
- Flarum version: 1.0.4
- Extension version: 1.0.2

**Comment by imorland** [comment]
Fixed in `1.0.3` - thanks for the report!
