### ISSUE TITLE
Ivalid URL when uses S3 compatibility storage

### ISSUE THREAD

**Issue by akamajoris** [FriendsOfFlarum/upload#297]
## Bug Report

Hi there.

**Steps to Reproduce**
1. Install extension, install s3 requirements
2. Configure module. Set Endpoint for example as https://s3.fr-par.scw.cloud/
3. Upload a file
4. See invalid link in the response 
```
[upl-image-preview url=https://<bucketname>.s3.fr-par.amazonaws.com/2021-09-10/1631276392-52976-ldpi.png]
```

**Expected Behavior**
The link should be `https://<bucketname>.s3.fr-par.scw.cloud/2021-09-10/1631276392-52976-ldpi.png`

The valid setting name of Endpoint is `awsS3Endpoint` not a `cdnUrl` that uses in the AwsS3.php file.
![image](https://user-images.githubusercontent.com/4648441/132852926-155b6dfd-3e45-4916-885a-e9bb51b09c8a.png)

**Possible solution(s)**
replace in file src/Adapters/AwsS3.php 
`$cdnUrl = $settings->get('fof-upload.cdnUrl');`
by 
`$settings->get('fof-upload.awsS3Endpoint');`

**Comment by imorland** [comment]
You should also add `Content Delivery URL (prefixes files)` (just above the S3 settings) to your required value.
