### ISSUE TITLE
Image embed in social media

### ISSUE THREAD

**Issue by MeowMeowVenom** [FriendsOfFlarum/upload#299]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Yes

A clear and concise description of what the problem is. eg. I have an issue when [...]
The image doesn't get embedded when sharing the post in social media

**Describe the solution you'd like**

A detailed description of your proposed solution. Include:
- How the feature would work/behave
- Any potential drawbacks
- Maybe a screenshot, design, or example code

When uploading an image, fof upload does something like this based on template '//host.com/image'. But, because of this, when sharing the post on social media, the image doesn't show up in the embed. But adding https: to the link solves the issue

**Describe alternatives you've considered**

Manually add https: to links after uploading

**Comment by clarkwinkelmann** [comment]
Which adapter/template are you using? From what I remember Upload should always use fully qualified URLs in the content.

Which social media can we experience this on? You mean when one image from the post is picked up as the OpenGraph default image, or some kind of rich embed like Discord where the actual post content could be rendered including formatting?

**Comment by Rejected-Peice** [comment]
I get this issue with all templates.
I tried sharing image on telegram and discord.
Adding https solves this issue
But, it would be nice to have that in the template.


By embed, I mean the preview that you get, by just sharing a link on any social media.

**Comment by DilipParasu** [comment]
If you have some time, then try making your own custom template.

https://github.com/FriendsOfFlarum/upload/wiki/Custom-Templates

**Comment by Rejected-Peice** [comment]
Yeah, suggested that to my friend, who does better php. Thx for that suggestion!

**Comment by DavideIadeluca** [comment]
Seems like this issue is resolved, as at least currently with `1.5.x`  the Open Graph Image is visible when sharing a discussion (which has a post with an image).

Therefore, this issue will be closed.
