### ISSUE TITLE
My media previews incompatible with webp images

### ISSUE THREAD

**Issue by iamdarkle** [FriendsOfFlarum/upload#322]
## Bug Report

In the "My media" section of the profile the image thumbnails seem to be unable to run webp images, regardless of the fact that the system and browser can render them.

**Comment by therealmaxmoon** [comment]
I can confirm this bug.

@iamdarkle Have you found a solution yet, because this issue is older than one year. It would be somehow helpful if there would be a [search field](https://github.com/FriendsOfFlarum/upload/issues/279) to at least filter by name, if thumbnails don't work.
