### ISSUE TITLE
I don't know what causes the error

### ISSUE THREAD

**Issue by moeik** [FriendsOfFlarum/upload#339]
After I finish configuring the theme and uploading files, I get an error of 500

![image](https://github.com/FriendsOfFlarum/upload/assets/49871008/45165d45-a121-4240-bdef-93652bde0ab7)
![image](https://github.com/FriendsOfFlarum/upload/assets/49871008/8345a280-e4c4-4e96-b09f-0c1ab372260e)
![image](https://github.com/FriendsOfFlarum/upload/assets/49871008/53ba3828-72dd-4997-8f36-18d5a2f4334e)
![image](https://github.com/FriendsOfFlarum/upload/assets/49871008/753d2be8-bed9-495c-8314-193128ad5875)

**Comment by luceos** [comment]
From this image: https://user-images.githubusercontent.com/49871008/248638251-8345a280-e4c4-4e96-b09f-0c1ab372260e.png

Can you share the contents in the Headers tab?
