### ISSUE TITLE
File Upload Names

### ISSUE THREAD

**Issue by OfficialAudite** [FriendsOfFlarum/upload#345]
I need to keep the name when downloading since it is ment for csgo maps and maps are with _ but the upload system replaces it with - and it does not work. Is there a way to fix it or change it ?

**Comment by luceos** [comment]
Check discord, implemented a hook and provided an example.

```
(new Extend\Event())
        ->listen(
            \FoF\Upload\Events\File\IsSlugged::class,
            fn (\FoF\Upload\Events\File\IsSlugged $event) => $event->slug = pathinfo($event->file->getClientOriginalName(), PATHINFO_FILENAME)
        ),
```
