### ISSUE TITLE
500 错误

### ISSUE THREAD

**Issue by acolasialiuliu** [FriendsOfFlarum/upload#351]
![图片](https://github.com/FriendsOfFlarum/upload/assets/62091678/0d1915c3-7550-4c02-a880-3f737d615b60)
我甚至无法发送文字，关闭插件就好了

**Comment by clarkwinkelmann** [comment]
Please post in English so we can better assist you.

If you encounter a 500 error, please retrieve the detailed error message from the Flarum log file. See https://docs.flarum.org/troubleshoot for how to do it.

Even with machine translation I don't understand your report. Please describe what you were attempting to do in more details, with steps to reproduce the problem on a different forum if possible.

Also please share as many details about your setup as possible. Are you self-hosting Flarum, which FoF Upload adapter are you using, what kind of file type have you uploaded, etc. Include your `php flarum info` of the forum so we can see other installed Flarum extensions and PHP version/extensions.

**Comment by acolasialiuliu** [comment]
Thanks for the reply, sorry, I'm also worried that machine translation will not be able to express it correctly
Here are the results of PHP Flarum Info

[root@VM-20-13-centos bbs]# php flarum info
Flarum core: 1.8.3
PHP version: 8.1.21
MySQL version: 8.0.24
Loaded extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, ctype, curl, dom, filter, ftp, gd, gettext, hash, iconv, intl, json, mbstring, SPL, session, pcntl, standard, mysqlnd, PDO, pdo_mysql, pdo_sqlite, Phar, posix, Reflection, mysqli, shmop, SimpleXML, soap, sockets, sodium, sysvsem, tokenizer, xml, xmlreader, xmlwriter, zip, memcached, imagick, exif, redis, apcu, fileinfo, Zend OPcache
+--------------------------------+---------+--------+
| Flarum Extensions              |         |        |
+--------------------------------+---------+--------+
| ID                             | Version | Commit |
+--------------------------------+---------+--------+
| flarum-flags                   | v1.8.0  |        |
| flarum-approval                | v1.8.0  |        |
| flarum-tags                    | v1.8.0  |        |
| yannisme-oxotheme              | 2.1.6   |        |
| fof-upload                     | 1.4.1   |        |
| flarum-suspend                 | v1.8.1  |        |
| flarum-subscriptions           | v1.8.0  |        |
| flarum-sticky                  | v1.8.0  |        |
| flarum-statistics              | v1.8.0  |        |
| flarum-nicknames               | v1.8.0  |        |
| flarum-mentions                | v1.8.2  |        |
| flarum-markdown                | v1.8.0  |        |
| flarum-lock                    | v1.8.0  |        |
| flarum-likes                   | v1.8.0  |        |
| flarum-lang-english            | v1.8.0  |        |
| flarum-lang-chinese-simplified | v1.3.0  |        |
| flarum-emoji                   | v1.8.0  |        |
| flarum-bbcode                  | v1.8.0  |        |
+--------------------------------+---------+--------+
Base URL: http://bbs.cathi.cn
Installation path: /www/wwwroot/bbs
Queue driver: sync
Session driver: file
Mail driver: smtp
Debug mode: off

//I tried my best to close other plugins and still get the error that I can't upload, even the basic text sending is wrong
![图片](https://github.com/FriendsOfFlarum/upload/assets/62091678/ccd5287e-3c0b-441b-90c0-1af4b8443dd7)

//Another problem is that clicking this button will prompt a hidden notification, if the notification is not allowed. You can't click this button. The normal logic should still work, but not prompt notifications
![图片](https://github.com/FriendsOfFlarum/upload/assets/62091678/0c9cbbaf-f467-4aee-848d-f35ea5c502b3)

All are machine translated, I hope you can understand, thanks
![图片](https://github.com/FriendsOfFlarum/upload/assets/62091678/d0e47d8e-5311-491e-9f16-ccb73b76a84f)

**Comment by acolasialiuliu** [comment]
Hi, I solved the problem with 500
![图片](https://github.com/FriendsOfFlarum/upload/assets/62091678/ef9e8c20-4f35-40ee-999e-15d70d729234)
![图片](https://github.com/FriendsOfFlarum/upload/assets/62091678/26678740-6e87-4fa9-82c7-6e5ebdb8d75f)
![图片](https://github.com/FriendsOfFlarum/upload/assets/62091678/4e2e6d60-6772-4381-9055-5ecbbdf18349)
and check the bucket's back-to-origin settings

However, some other problems were found, such as the second image above, which cannot be customized for the storage path, which is not friendly to multiple sites per machine. The problem of deleting the notification being rejected still exists, and I don't know how to restart the notification, so I can only operate it in a different browser haha

**Comment by acolasialiuliu** [comment]
Despite the success of uploading the image, the publishing still fails, alas
![图片](https://github.com/FriendsOfFlarum/upload/assets/62091678/ccd6be31-58d3-461f-9f23-e4cf56025c9c)

**Comment by luceos** [comment]
Was this resolved or why did you close the issue @acolasialiuliu ?

**Comment by acolasialiuliu** [comment]
> Was this resolved or why did you close the issue @acolasialiuliu ?

Yes, I solved it. By the way, I learned debugs, which are part of the errors caused by my database format. And turn off the Pusher plugin
