### ISSUE TITLE
PDF files are not displayed

### ISSUE THREAD

**Issue by cedpar** [FriendsOfFlarum/upload#357]
## Bug Report

**Current Behavior**
PDF files are not displayed

**Steps to Reproduce**
1. Upload a PDF file
2. View conversation
3. PDF file is not displayed

**Expected Behavior**
Problem with upl-image-preview

**Screenshots**
With Safari :
<img width="642" alt="Capture d’écran 2023-11-08 à 09 29 38" src="https://github.com/FriendsOfFlarum/upload/assets/150233702/35bc83a9-10ad-4d80-8e51-884683b5c6a5">
<img width="519" alt="Capture d’écran 2023-11-08 à 09 29 42" src="https://github.com/FriendsOfFlarum/upload/assets/150233702/ae35d453-00f6-481c-b9a2-a17ea768c003">

With Chrome : 
<img width="864" alt="Capture d’écran 2023-11-08 à 09 29 26" src="https://github.com/FriendsOfFlarum/upload/assets/150233702/b17f2d2e-8e1d-4c28-935d-b85bf20e08ea">

**Environment**
- Flarum version:  1.8.3
- Extension version:  FoF Upload 1.4.4
- Website URL: http://www.rvo95.fr
- Webserver: Apache 2.4.51
- Hosting environment: Shared Infomaniak
- PHP version: 8.2.9
- Browser:  **DON'T WORK on Chrome 119.0.6045.123 + Brave 1.60.110 + Firefox 119.0.1 on macOs 14.1.1, Chrome 119.0.6045.66 + Firefox 119.0.1 on Android 11**
- Browser : _WORK on Safari 17.1 on macOs 14.1.1, Chrome 119.0.6045.101 + Brave 1.58 on iOs 17.1.1_

```
Flarum core: 1.8.3
PHP version: 8.1.22
MySQL version: 10.4.19-MariaDB-1:10.4.19+maria~stretch-log
Loaded extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, gettext, gmp, json, iconv, SPL, intl, session, ldap, mbstring, standard, pcntl, PDO, mysqlnd, pdo_sqlite, pgsql, Phar, posix, readline, Reflection, imap, SimpleXML, soap, sockets, sodium, pdo_mysql, exif, tidy, tokenizer, xml, xmlreader, xmlwriter, xsl, mysqli, imagick, mailparse, mcrypt, memcached, mongodb, OAuth, raphf, ssh2, timezonedb, uploadprogress, yaz, zip, http
+---------------------+---------+--------+
| Flarum Extensions   |         |        |
+---------------------+---------+--------+
| ID                  | Version | Commit |
+---------------------+---------+--------+
| flarum-tags         | v1.8.0  |        |
| flarum-sticky       | v1.8.0  |        |
| flarum-nicknames    | v1.8.0  |        |
| flarum-lock         | v1.8.0  |        |
| flarum-flags        | v1.8.0  |        |
| kilowhat-audit-free | 1.7.0   |        |
| fof-upload          | 1.4.4   |        |
| fof-links           | 1.2.0   |        |
| fof-geoip           | 1.3.0   |        |
| flarum-statistics   | v1.8.0  |        |
| flarum-mentions     | v1.8.2  |        |
| flarum-markdown     | v1.8.0  |        |
| flarum-lang-french  | v4.17.0 |        |
| flarum-emoji        | v1.8.0  |        |
+---------------------+---------+--------+
Base URL: https://www.rvo95.fr
Installation path: /home/clients/c9af3a0d6b529bf7f121c4804dc1d9fa/sites/rvo95.fr
Queue driver: sync
Session driver: file
Mail driver: smtp
Debug mode: off
```

**Additional Context**
I tried to change the MIME type but it doesn't work

**Comment by clarkwinkelmann** [comment]
the upl-image-preview is only designed to preview files that are natively stored as images. In practice it should allow previewing any file that a browser can render inside of an `<img src="">` tag. I suppose Safari somehow implemented PDF as a valid IMG source when all other browsers have not.

I am not finding any official documentation on why Safari choose to implement this and how it's supposed to work. The only relevant result seems to be this StackOverflow question but it doesn't lead to any useful information https://stackoverflow.com/questions/70193677/chrome-does-not-allow-me-to-use-pdf-in-img-tag In any case I doubt any browser is actively working to implement such a feature. I don't believe it's part of any web standard existing or in development.

FoF Upload does not have any native way to preview PDFs. Another extension could provide a new template that does. An easy solution would be to render the PDF in an iframe as it would take advantage of the browser ability to render a PDF viewer, but this would be dangerous to safeguard against XSS vectors. A safer solution would be an extension that implements a server-side rendering of a preview image and returns it to the frontend in a new template. I doubt either of these options would be added to FoF Upload directly at this moment as they require significant work and increase the maintenance burden.

If you still believe this is a bug with an existing FoF Upload feature, feel free to re-open the issue with more details.
