### ISSUE TITLE
Upload your watermark image is not work

### ISSUE THREAD

**Issue by hiepvq** [FriendsOfFlarum/upload#376]
Can not Upload your watermark image

**Comment by clarkwinkelmann** [comment]
We need more details. Please share your `php flarum info` output and any relevant error message. See https://docs.flarum.org/troubleshoot

**Comment by hiepvq** [comment]
Flarum core: 1.8.3
PHP version: 8.1.25

**Comment by imorland** [comment]
I can confirm this issue, I'll work on a fix..
