### ISSUE TITLE
Enable watermark images, uploader is not placed the processed image to the editor's content

### ISSUE THREAD

**Issue by hiepvq** [FriendsOfFlarum/upload#385]
## Bug Report

I see the image is processed with watermark but it doesn't place image tothe editor's content immediately.

This bug is an error js code
![Screenshot 2023-12-16 215113](https://github.com/FriendsOfFlarum/upload/assets/36187674/d186c75b-c074-4b74-aa9e-f6f064b85fda)

![Screenshot 2023-12-16 215304](https://github.com/FriendsOfFlarum/upload/assets/36187674/83ebe888-6425-4393-bf41-70755db2d38e)

i have not tried on local storage yet. I am using S3 storage.

**Environment**
- Flarum core: 1.8.3
- PHP version: 8.1.26
- Upload version: Checkout code from master

**Comment by imorland** [comment]
What is `emojifiedContentHtml` and where does that come from? At first glance this appears to be an issue stemming from another extension

**Comment by hiepvq** [comment]
No, it still works when i disabled watermark

**Comment by clarkwinkelmann** [comment]
> What is `emojifiedContentHtml` and where does that come from?

@imorland it's the core emoji extension :wink:

https://github.com/flarum/framework/blob/v1.8.3/extensions/emoji/js/src/forum/renderEmoji.js#L46
