### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by pkoevesdi** [FriendsOfFlarum/upload#402]
When I try to install `composer require fof/upload "*"` with extension manager, I get the error message "package Format invalid". How can I install this?

**Comment by DavideIadeluca** [comment]
@pkoevesdi Yep, the instructions on how to install this extension were wrong (fixed with https://github.com/FriendsOfFlarum/upload/pull/403)

`composer require fof/upload:"*"` is the correct command how to install
