### ISSUE TITLE
Responsive images

### ISSUE THREAD

**Issue by jtojnar** [FriendsOfFlarum/upload#69]
Complementing the [lightbox feature](https://github.com/flagrow/upload/issues/46), multiple thumbnails of various sizes could be generated and then offered via [srcset](https://css-tricks.com/responsive-images-youre-just-changing-resolutions-use-srcset/) attribute.

**Comment by Luceos** [comment]
This would only be a valid option for a Local adapter. And even then, the current set up is that we upload one file so we can track its use and allow deletion of it.

**Comment by DavideIadeluca** [comment]
Closed as a consequence of #46
