### ISSUE TITLE
Allow optimizing images

### ISSUE THREAD

**Issue by jtojnar** [FriendsOfFlarum/upload#78]
Since the images are not [responsive](https://github.com/flagrow/upload/issues/69) yet, I would like to process each uploaded image using `pngcrush` to somewhat lower the size of the downloaded images.

**Comment by Luceos** [comment]
pngcrush is something someone would have to install, correct?

**Comment by jtojnar** [comment]
Indeed.

**Comment by clarkwinkelmann** [comment]
Wow we've got some old issues here.

I don't know when it was implemented, but it's currently possible to run code similar to the `ImageProcessor` that takes care of the watermark and size limitations. So it should be no problem for a third-party developer to implement it.

I suppose we won't implement this ourselves into the extension. Though conversions could be nice for previews.

**Comment by luceos** [comment]
Yeah I think this is not something we would take care of ourselves..
