### ISSUE TITLE
OpenGraph Issues

### ISSUE THREAD

**Issue by AngellitoX** [FriendsOfFlarum/upload#92]
- flagrow/upload extension version: 0.5.X last version (cant remember the number sorry hehe)
- flarum version: 0.1.0-beta.6
- Upload adapter causing issues: Global
---
 In much earlier versions the pictures uploaded with Flagrow Upload inside a post used to be caught by OpenGraph metadata which made the links shared in social networks much more eye-attractive. This feature is gone since version 0.5.0.

Thank you in advance :D

**Comment by DavideIadeluca** [comment]
I don't know when this issue was resolved, but the scenario you described is working again.
